import { pass } from '@toktokhan-dev/universal'

import { isObject } from 'lodash'
import { flow, identity, invert, mapKeys, mapValues, replace } from 'lodash/fp'

import { SwatTextStyleMode, TextStyleModes, ThemeToken } from './type'
import { ifElse } from './utils/if-else'
import { throwError } from './utils/throw-error'

const getTextStylesKey: (str: string) => string = flow(
  replace(/\s/g, ''),
  replace(/-/g, '.'),
)
/**
 * 주어진 객체의 키를 제공된 키 맵에 따라 매핑합니다. 키 맵에 존재하지 않는 키가 있을 경우,
 * 해당 키가 tokenMode에서 유효하지 않다는 메시지를 로그로 출력합니다.
 * @param obj - 키를 매핑할 객체입니다.
 * @param keyMap - 기존 키를 새로운 키로 매핑하는 객체입니다.
 * @returns 키가 매핑된 새로운 객체를 반환합니다.
 */
const matchKey =
  (keyMap?: SwatTextStyleMode) => (obj: ArrayLike<string | number>) =>
    mapKeys((key: string) => {
      if (!keyMap || Object.keys(keyMap).length === 0) {
        return throwError(`The given value requires tokenMode.`)
      }
      if (!keyMap?.[key]) {
        return throwError(`This "${key}" is not a valid value in tokenMode.`)
      }
      return keyMap[key]
    })(obj)

/**
 * 주어진 JSON 객체의 텍스트 스타일을 변환합니다.
 *
 * @param json - 변환할 텍스트 스타일 객체입니다.
 * @param mode - 선택적 키 매핑 객체입니다. 이 객체는 텍스트 스타일의 키를 변환하는 데 사용됩니다.
 * @returns 변환된 텍스트 스타일 객체를 반환합니다.
 */
const getTextStyleObj = (
  json: ThemeToken['textStyles'],
  mode: SwatTextStyleMode,
) =>
  flow(
    pass(json),
    mapKeys(getTextStylesKey),
    mapValues(mapValues(ifElse(isObject, matchKey(mode), identity))),
  )()

/**
 * 주어진 JSON 객체를 기반으로  chakra-ui theme 에 사용될 파일 컨텐츠를 생성합니다.
 *
 * @param json textStyles의 ThemeToken 객체입니다.
 * @param tokenModes - textStyles 모드 객체입니다.
 * @returns chakra-ui theme에 적용가능한 textStyle이 출력됩니다.
 */

export const renderTextStyle = (
  json: ThemeToken['textStyles'],
  tokenModes: TextStyleModes,
): string => {
  const modes = tokenModes
  const swapMode = invert(modes) as SwatTextStyleMode
  const textStyle = getTextStyleObj(json, swapMode)
  return `
    /**
     * !DO NOT EDIT THIS FILE
     * 
     * generated by script: tokript gen:theme
     * 
     * theme text style 을 정의하는 곳입니다.
     *
     * @see https://chakra-ui.com/docs/styled-system/semantic-tokens
    **/
    
    export const textStyles = ${JSON.stringify(textStyle, null, 2)}
  `
}
