packages:
  # Apps
  - 'apps/*'
  - 'apps/docs/plugins/doc-plugin'

  # Configs
  - 'configs/*'

  # Packages
  - 'packages/*'
  - 'packages/react/universal'
  - 'packages/react/web'
  - 'packages/cli-plugins/*'
  - 'packages/zustand/*'

  # # Templates
  - 'templates/*'
  - 'templates/rn-native-base/template'
allowBuilds:
  core-js: true
  core-js-pure: true
  esbuild: true
  protobufjs: true
  sharp: true
